# ------------------------------------连接池配置------------------------------------------
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.128.163.160:3306/jdbc1?useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: cloudwalk
    password: Cloudwalk@123!
    # 执行时显示SQL语句
    props:
      # 日志显示具体的SQL
      sql-show: true
# ------------------------------------mybatis-plus配置------------------------------------------
mybatis-plus:
  #  mapper-locations: classpath*:**/mapper/*.xml
  type-aliases-package: com.cw.cbs.wh.algorithm.entity.**
  check-config-location: true
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: partial
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: input
